# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('name', models.CharField(default=b'', max_length=200)),
                ('digest', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=16, unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
