# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0005_authtoken_token_key'),
    ]

    operations = [
    ]
